// Auto-generated by scripts/bundle-ruby.js
// DO NOT EDIT THIS FILE DIRECTLY - edit lib/homura.rb and app/routes.rb instead

export const HOMURA_CORE = `# Homura - A Hono-like Ruby DSL for Cloudflare Workers
# This file is the framework core - users don't need to modify this

class Homura
  def initialize
    @routes = {}
    @not_found = nil
  end

  def get(path, &block)
    @routes[["GET", path]] = block
  end

  def post(path, &block)
    @routes[["POST", path]] = block
  end

  def put(path, &block)
    @routes[["PUT", path]] = block
  end

  def patch(path, &block)
    @routes[["PATCH", path]] = block
  end

  def delete(path, &block)
    @routes[["DELETE", path]] = block
  end

  def match_route(method, path)
    path_parts = path.split("/").reject { |p| p.empty? }
    @routes.each do |(route_method, pattern), handler|
      next unless route_method == method
      pattern_parts = pattern.split("/").reject { |p| p.empty? }
      next unless pattern_parts.length == path_parts.length

      params = {}
      matched = true
      pattern_parts.each_with_index do |part, idx|
        if part.start_with?(":")
          params[part[1..-1].to_sym] = path_parts[idx]
        elsif part != path_parts[idx]
          matched = false
          break
        end
      end

      return [handler, params] if matched
    end
    nil
  end

  def call(env)
    result = match_route(env[:method], env[:path])
    if result
      handler, params = result
      ctx = Context.new(env, params)
      response = handler.call(ctx)
      response[:kv_ops] = ctx.kv_ops if ctx.kv_ops && !ctx.kv_ops.empty?
      response
    else
      if @not_found
        ctx = Context.new(env, {})
        response = @not_found.call(ctx)
        response[:kv_ops] = ctx.kv_ops if ctx.kv_ops && !ctx.kv_ops.empty?
        response
      else
        { status: 404, body: "Not Found", headers: {} }
      end
    end
  end

  def not_found(&block)
    @not_found = block
  end
end

class Context
  attr_reader :params, :env

  def initialize(env, params)
    @env = env
    @params = params
    @kv_ops = []
  end

  def body
    @env[:body] || ""
  end

  def json_body
    body_str = body
    return {} if body_str.nil? || body_str.empty?
    body_str
  end

  # KV operations
  def kv_get(key)
    kv_data = @env[:kv_data] || {}
    kv_data[key.to_s]
  end

  def kv_put(key, value)
    @kv_ops << { op: "put", key: key.to_s, value: value.to_s }
  end

  def kv_delete(key)
    @kv_ops << { op: "delete", key: key.to_s }
  end

  def kv_ops
    @kv_ops
  end

  # Response helpers
  def json(data, status: 200)
    { status: status, body: data, headers: { "Content-Type" => "application/json" } }
  end

  def text(body, status: 200)
    { status: status, body: body, headers: { "Content-Type" => "text/plain" } }
  end

  def html(body, status: 200)
    { status: status, body: body, headers: { "Content-Type" => "text/html" } }
  end

  def jsx(template, props = {}, status: 200)
    { status: status, type: "jsx", template: template, props: props, headers: { "Content-Type" => "text/html" } }
  end

  def css(body, status: 200, max_age: 0, etag: nil)
    headers = { "Content-Type" => "text/css" }
    headers["Cache-Control"] = "public, max-age=#{max_age}" if max_age && max_age > 0
    headers["ETag"] = etag if etag
    { status: status, body: body, headers: headers }
  end
end

module View
  def self.h(text)
    s = text.to_s
    out = ""
    s.each_byte do |b|
      case b
      when 38 then out << "&amp;"
      when 60 then out << "&lt;"
      when 62 then out << "&gt;"
      when 34 then out << "&quot;"
      when 39 then out << "&#39;"
      else out << b.chr
      end
    end
    out
  end
end

class Object
  def to_json
    case self
    when NilClass then "null"
    when TrueClass then "true"
    when FalseClass then "false"
    when Integer, Float then self.to_s
    when String then "\\"" + self.gsub("\\\\", "\\\\\\\\").gsub("\\"", "\\\\\\"") + "\\""
    when Symbol then "\\"" + self.to_s + "\\""
    when Array then "[" + self.map { |e| e.to_json }.join(",") + "]"
    when Hash then "{" + self.map { |k, v| "\\"#{k}\\":" + v.to_json }.join(",") + "}"
    else "\\"" + self.to_s + "\\""
    end
  end
end

def parse_json(str)
  return {} if str.nil? || str.empty?
  str = str.strip
  return nil if str == "null"
  return true if str == "true"
  return false if str == "false"

  if str.length > 0 && (str[0] == "-" || (str[0] >= "0" && str[0] <= "9"))
    return str.include?(".") ? str.to_f : str.to_i
  end

  if str.start_with?("\\"") && str.end_with?("\\"")
    return str[1..-2]
  end

  if str.start_with?("{") && str.end_with?("}")
    result = {}
    content = str[1..-2].strip
    return result if content.empty?

    pairs = []
    depth = 0
    current = ""
    content.each_char do |c|
      if c == "{" || c == "["
        depth += 1
        current << c
      elsif c == "}" || c == "]"
        depth -= 1
        current << c
      elsif c == "," && depth == 0
        pairs << current.strip
        current = ""
      else
        current << c
      end
    end
    pairs << current.strip unless current.empty?

    pairs.each do |pair|
      colon_idx = nil
      in_string = false
      pair.each_char.with_index do |c, i|
        if c == "\\"" && (i == 0 || pair[i-1] != "\\\\")
          in_string = !in_string
        elsif c == ":" && !in_string
          colon_idx = i
          break
        end
      end

      if colon_idx
        key_part = pair[0...colon_idx].strip
        val_part = pair[(colon_idx+1)..-1].strip
        if key_part.start_with?("\\"") && key_part.end_with?("\\"")
          key = key_part[1..-2].to_sym
          result[key] = parse_json(val_part)
        end
      end
    end
    return result
  end

  str
end

\$app = Homura.new
`;

export const USER_ROUTES = `# Homura Routes - Define your application routes here
# This is the main file you'll edit to build your app

# ===== CSS =====
APP_CSS = <<~CSS
:root {
  color-scheme: light;
  --bg: #f6f1e7;
  --text: #1f1a14;
  --muted: #6b5f54;
  --accent: #b44d2f;
  --accent-2: #256b7e;
  --card: #ffffff;
  --shadow: rgba(31, 26, 20, 0.12);
}

* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: "Hiragino Sans", "Noto Sans JP", "Yu Gothic", sans-serif;
  background: linear-gradient(180deg, #f6f1e7 0%, #efe6d7 100%);
  color: var(--text);
}

a { color: inherit; text-decoration: none; }
.container { max-width: 960px; margin: 0 auto; padding: 0 24px; }

.site-header {
  padding: 20px 0;
  border-bottom: 1px solid rgba(31, 26, 20, 0.08);
  background: rgba(255, 255, 255, 0.6);
  backdrop-filter: blur(10px);
}

.logo { font-weight: 700; font-size: 20px; letter-spacing: 0.04em; }
.nav { display: flex; gap: 16px; font-size: 14px; }
.site-header .container { display: flex; justify-content: space-between; align-items: center; }

.hero { padding: 56px 0 32px; }
.eyebrow { text-transform: uppercase; letter-spacing: 0.12em; font-size: 12px; color: var(--muted); }
.hero h1 { font-size: 40px; margin: 8px 0; }
.lead { color: var(--muted); font-size: 18px; max-width: 620px; }

.actions { display: flex; gap: 12px; margin-top: 24px; }
.button {
  padding: 10px 18px;
  border-radius: 999px;
  background: var(--accent);
  color: #fff;
  font-weight: 600;
}
.button.ghost {
  background: transparent;
  color: var(--accent);
  border: 1px solid var(--accent);
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 16px;
  margin-bottom: 40px;
}
.card {
  background: var(--card);
  border-radius: 16px;
  padding: 16px;
  box-shadow: 0 10px 30px var(--shadow);
}

.stack { padding: 40px 0; }
.list { padding-left: 20px; color: var(--muted); }

.site-footer {
  padding: 24px 0 40px;
  color: var(--muted);
  font-size: 12px;
}

/* Counter Section */
.counter-section { padding: 32px 0; display: flex; justify-content: center; }
.counter-card {
  background: var(--card);
  border-radius: 24px;
  padding: 32px 48px;
  box-shadow: 0 10px 40px var(--shadow);
  text-align: center;
  min-width: 320px;
}
.counter-card h2 { margin: 0 0 8px; color: var(--accent); }
.counter-desc { color: var(--muted); font-size: 14px; margin: 0 0 24px; }
.counter-display {
  font-size: 72px;
  font-weight: 700;
  color: var(--accent-2);
  margin: 16px 0;
  font-feature-settings: "tnum";
}
.counter-actions { display: flex; gap: 12px; justify-content: center; margin-top: 16px; }
.counter-actions button { cursor: pointer; border: none; font-size: 16px; }
.counter-status { margin-top: 16px; font-size: 14px; color: var(--muted); min-height: 20px; }
CSS

# ===== Pages =====

\$app.get "/" do |c|
  current_count = c.kv_get("counter") || "0"
  c.jsx("home", { counter: current_count })
end

\$app.get "/hello/:name" do |c|
  safe_name = View.h(c.params[:name])
  c.html("<h1>Hello, " + safe_name + "!</h1><p>Homura - Ruby on the Edge</p>")
end

# ===== API =====

\$app.get "/api" do |c|
  c.json({ message: "Hello from Homura!", framework: "mruby + WASI", version: "0.1.0" })
end

\$app.get "/health" do |c|
  c.json({ status: "ok", runtime: "cloudflare-workers", engine: "mruby" })
end

# ===== Users CRUD =====

\$app.get "/users/:id" do |c|
  c.json({ user_id: c.params[:id], action: "show" })
end

\$app.post "/users" do |c|
  c.json({ action: "create", body: c.body }, status: 201)
end

\$app.put "/users/:id" do |c|
  c.json({ action: "update", user_id: c.params[:id], body: c.body })
end

\$app.patch "/users/:id" do |c|
  c.json({ action: "patch", user_id: c.params[:id], body: c.body })
end

\$app.delete "/users/:id" do |c|
  c.json({ action: "delete", user_id: c.params[:id] })
end

# ===== KV Counter =====

\$app.get "/counter" do |c|
  current = c.kv_get("counter")
  count = current ? current.to_i : 0
  new_count = count + 1
  c.kv_put("counter", new_count.to_s)
  c.json({ count: new_count, message: "Counter incremented!" })
end

\$app.post "/counter/reset" do |c|
  c.kv_put("counter", "0")
  c.json({ count: 0, message: "Counter reset!" })
end

# ===== KV Users =====

\$app.post "/kv/users/:name" do |c|
  name = c.params[:name]
  c.kv_put("user:" + name, c.body)
  c.json({ saved: name, body: c.body }, status: 201)
end

\$app.get "/kv/users/:name" do |c|
  name = c.params[:name]
  data = c.kv_get("user:" + name)
  if data
    c.json({ user: name, data: data })
  else
    c.json({ error: "User not found" }, status: 404)
  end
end

\$app.delete "/kv/users/:name" do |c|
  name = c.params[:name]
  c.kv_delete("user:" + name)
  c.json({ deleted: name })
end

# ===== Assets =====

\$app.get "/assets/app.css" do |c|
  c.css(APP_CSS)
end
`;
