name = "homura-template-engine"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[build]
command = "npm run bundle:ruby"
watch_dir = ["app", "../../lib"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
